MOST
xSPO-Alliance/adapools-xspo-alliance pull request #205
Opened 2022-02-23 20:09 UTC by Danmcg86

2022-02-23 20:13 UTC, Danmcg86 commented
Hope I got it right this time

2022-02-24 10:59 UTC, cardano-apexpool requested changes

2022-02-24 10:59 UTC, cardano-apexpool commented on xspo-alliance-members.json
>        }
Please remove the line above.

2022-02-24 10:59 UTC, cardano-apexpool commented on xspo-alliance-members.json
>  }
Please add a new line after this (an enter after "}").

2022-02-25 03:58 UTC, closed without merging